[theme]

# The preset Streamlit theme that your custom theme inherits from.
# One of "light" or "dark".
base = "light"

# Primary accent color for interactive elements.
primaryColor = "#4C3B8F"

# Background color for the main content area.
backgroundColor = "#f9fafb"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#ffffff"

# Color used for almost all text.
textColor = "#030712"

# Font family for all text in the app, except code blocks. One of "sans serif",
# "serif", or "monospace".
# font =